'use strict';
const I18N={ko:{appTitle:'리그 오브 레전드',statLabel:'명 등록됨',btnAdd:'참가자 추가',btnReset:'초기화',btnMatch:'팀 밸런스 맞추기',resultTitle:'팀 편성 완료',balanceLabel:'팀 점수 밸런스',btnBack:'돌아가기',btnReroll:'Reroll',btnNext:'다음',btnSkip:'건너뛰기',btnFinish:'등록 완료',btnDelete:'삭제',btnCopy:'디스코드 복사',toastCopied:'클립보드에 복사됐어요',scoreLabel:'점수',totalScore:'총점',comboLabel:'최적 밸런스 조합',noCombo:'조합 없음',errorMsg:'조건을 만족하는 팀을 짤 수 없습니다.',warnRelaxed:'티어 불균형으로 인해 밸런스 조건이 완화되었습니다',conflictTitle:'조건 충돌',conflictMsg:'필수/기피 동료 조건이 충돌합니다.\n조건을 무시하고 티어 밸런스만 맞출까요?',btnForceMatch:'강제 매칭',btnCancel:'취소',confirmReset:'모든 참가자를 초기화할까요?',toastAdded:'등록 완료!',toastDeleted:'삭제됨',toastCombo:'조합',emptyHint:'참가자를 추가해주세요',emptyHintSub:'최대 10명까지 등록할 수 있어요',noPlayers:'아직 등록된 참가자가 없습니다',nameRequired:'이름을 입력해주세요',inputPlaceholder:'소환사 이름 입력',stepTitles:['이름 입력','티어 선택','세부 티어','선호 라인','필수 동료','기피 동료'],stepLabels:['Step 1 — 이름','Step 2 — 티어','Step 3 — 세부 티어','Step 4 — 라인','Step 5 — 필수 동료','Step 6 — 기피 동료'],masterLpLabel:'마스터 LP 구간',tiers:['아이언','브론즈','실버','골드','플래티넘','에메랄드','다이아몬드','마스터','그랜드마스터','챌린저'],tierShort:['I','B','S','G','P','E','D','M','GM','C'],masterLp:['저점 (0~200LP)','고점 (200LP+)'],lanes:['탑','정글','미드','원딜','서포터','상관없음'],blueTeam:'BLUE 팀',redTeam:'RED 팀',sectionPlayers:'참가자',placeholderTitle:'팀이 구성되면 여기에 표시됩니다',placeholderSub:'10명을 등록하고 팀 밸런스 맞추기를 눌러주세요',algoInfo:'알고리즘 안내: 입력된 소환사들의 티어 점수 총합을 계산한 뒤, 두 팀의 평균 점수 격차가 가장 최소화되도록 수만 번의 조합을 계산하여 가장 황금 밸런스를 가진 블루팀과 레드팀을 구성합니다.'},
en:{appTitle:'League of Legends',statLabel:'registered',btnAdd:'Add Player',btnReset:'Reset',btnMatch:'Balance Teams',resultTitle:'Teams Ready',balanceLabel:'Score Balance',btnBack:'Back',btnReroll:'Reroll',btnNext:'Next',btnSkip:'Skip',btnFinish:'Add',btnDelete:'Remove',btnCopy:'Copy for Discord',toastCopied:'Copied!',scoreLabel:'Score',totalScore:'Total',comboLabel:'Best Combo',noCombo:'No Combo',errorMsg:'Cannot form valid teams.',warnRelaxed:'Balance filters relaxed',conflictTitle:'Conflict',conflictMsg:'Constraints conflict.\nIgnore and balance by tier?',btnForceMatch:'Force',btnCancel:'Cancel',confirmReset:'Reset all?',toastAdded:'added!',toastDeleted:'removed',toastCombo:'Combo',emptyHint:'Add players to get started',emptyHintSub:'Up to 10 players',noPlayers:'No players yet',nameRequired:'Enter a name',inputPlaceholder:'Summoner name',stepTitles:['Name','Tier','Sub Tier','Lane','Must-Play','Avoid'],stepLabels:['Step 1 — Name','Step 2 — Tier','Step 3 — Sub Tier','Step 4 — Lane','Step 5 — Must-Play','Step 6 — Avoid'],masterLpLabel:'Master LP',tiers:['Iron','Bronze','Silver','Gold','Platinum','Emerald','Diamond','Master','Grandmaster','Challenger'],tierShort:['I','B','S','G','P','E','D','M','GM','C'],masterLp:['Low LP','High LP'],lanes:['Top','Jungle','Mid','ADC','Support','Flex'],blueTeam:'BLUE',redTeam:'RED',sectionPlayers:'Players',placeholderTitle:'Results will appear here',placeholderSub:'Register 10 players and click Balance Teams',algoInfo:'Algorithm Guide: Calculates the total tier scores of the summoners, computes tens of thousands of combinations, and forms the Blue and Red teams with the most golden balance to minimize the average score gap.'},
ja:{appTitle:'リーグ・オブ・レジェンド',statLabel:'人登録済み',btnAdd:'追加',btnReset:'リセット',btnMatch:'バランス調整',resultTitle:'編成完了',balanceLabel:'スコアバランス',btnBack:'戻る',btnReroll:'リロール',btnNext:'次へ',btnSkip:'スキップ',btnFinish:'登録',btnDelete:'削除',btnCopy:'コピー',toastCopied:'コピーしました',scoreLabel:'スコア',totalScore:'合計',comboLabel:'最適組合せ',noCombo:'なし',errorMsg:'条件を満たせません',warnRelaxed:'条件緩和',conflictTitle:'競合',conflictMsg:'条件が競合しています',btnForceMatch:'強制',btnCancel:'キャンセル',confirmReset:'リセットしますか？',toastAdded:'登録完了',toastDeleted:'削除',toastCombo:'組合せ',emptyHint:'追加してください',emptyHintSub:'最大10人',noPlayers:'未登録',nameRequired:'名前を入力',inputPlaceholder:'サモナー名',stepTitles:['名前','ティア','サブ','レーン','必須','回避'],stepLabels:['Step 1','Step 2','Step 3','Step 4','Step 5','Step 6'],masterLpLabel:'マスターLP',tiers:['アイアン','ブロンズ','シルバー','ゴールド','プラチナ','エメラルド','ダイヤ','マスター','グラマス','チャレ'],tierShort:['I','B','S','G','P','E','D','M','GM','C'],masterLp:['低LP','高LP'],lanes:['トップ','JG','ミッド','ADC','サポ','フレックス'],blueTeam:'BLUE',redTeam:'RED',sectionPlayers:'プレイヤー',placeholderTitle:'結果表示エリア',placeholderSub:'10人登録してください',algoInfo:'アルゴリズム案内: サモナーのティアスコア合計を計算し、数万通りの組み合わせから平均スコア差が最小となるブルーチームとレッドチームを構成します。'},
zh:{appTitle:'英雄联盟',statLabel:'已注册',btnAdd:'添加',btnReset:'重置',btnMatch:'平衡队伍',resultTitle:'编排完成',balanceLabel:'分数平衡',btnBack:'返回',btnReroll:'重新分配',btnNext:'下一步',btnSkip:'跳过',btnFinish:'完成',btnDelete:'删除',btnCopy:'复制',toastCopied:'已复制',scoreLabel:'分数',totalScore:'总分',comboLabel:'最优组合',noCombo:'无',errorMsg:'无法组队',warnRelaxed:'条件放宽',conflictTitle:'冲突',conflictMsg:'条件冲突，忽略条件？',btnForceMatch:'强制',btnCancel:'取消',confirmReset:'确定重置？',toastAdded:'完成',toastDeleted:'已删除',toastCombo:'组合',emptyHint:'请添加玩家',emptyHintSub:'最多10人',noPlayers:'暂无',nameRequired:'请输入',inputPlaceholder:'召唤师名',stepTitles:['名称','段位','细分','路线','同队','回避'],stepLabels:['Step 1','Step 2','Step 3','Step 4','Step 5','Step 6'],masterLpLabel:'大师LP',tiers:['黑铁','黄铜','白银','黄金','铂金','翡翠','钻石','宗师','王者','挑战者'],tierShort:['I','B','S','G','P','E','D','M','GM','C'],masterLp:['低LP','高LP'],lanes:['上路','打野','中路','ADC','辅助','随意'],blueTeam:'蓝队',redTeam:'红队',sectionPlayers:'玩家',placeholderTitle:'结果显示区',placeholderSub:'注册10人后点击平衡',algoInfo:'算法说明: 计算召唤师的段位分数总和，通过数万次组合计算，组建平均分差最小的蓝队和红队。'}};
const TIER_KEYS=['아이언','브론즈','실버','골드','플래티넘','에메랄드','다이아몬드','마스터','그랜드마스터','챌린저'],TIER_COLORS={'아이언':'#8B8B8B','브론즈':'#A0522D','실버':'#708090','골드':'#B8860B','플래티넘':'#2E8B57','에메랄드':'#00A86B','다이아몬드':'#4169E1','마스터':'#9B59B6','그랜드마스터':'#C0392B','챌린저':'#E67E22'},SCORES={'아이언':[1,1.2,1.4,1.6],'브론즈':[2,2.2,2.4,2.6],'실버':[3,3.3,3.6,3.9],'골드':[4.5,4.9,5.3,5.7],'플래티넘':[6.5,7,7.5,8],'에메랄드':[9.5,10.2,10.9,11.6],'다이아몬드':[13.5,14.5,15.5,16.5],'마스터':null,'그랜드마스터':32,'챌린저':40},MLP={0:21,1:26},LANE_KEYS=['탑','정글','미드','원딜','서포터','상관없음'],LANE_LBL={'탑':'T','정글':'J','미드':'M','원딜':'A','서포터':'S','상관없음':'·'},LANE_ORD=['탑','정글','미드','원딜','서포터'],NO_SUB=['마스터','그랜드마스터','챌린저'];
let players=[],matchResults=[],curIdx=0,step=1,draft={},lang='ko',mode='normal';
const t=k=>I18N[lang]?.[k]??I18N.ko[k]??k,$=id=>document.getElementById(id),esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function save(){localStorage.setItem('lol_players',JSON.stringify(players))}function load(){try{players=JSON.parse(localStorage.getItem('lol_players')||'[]')}catch{players=[]}lang=localStorage.getItem('tm_lang')||'ko'}
function calcScore(p){const k=p.tierKey;if(k==='그랜드마스터')return 32;if(k==='챌린저')return 40;if(k==='마스터')return MLP[p.masterLpIdx]??21;const a=SCORES[k];return a?a[Math.max(0,Math.min(3,4-parseInt(p.subTier)))]:0;}
function tierDisp(p){const ts=t('tiers'),i=TIER_KEYS.indexOf(p.tierKey),n=ts[i]||p.tierKey;if(NO_SUB.includes(p.tierKey))return p.tierKey==='마스터'?`${n} (${t('masterLp')[p.masterLpIdx]||''})`:n;return`${n} ${p.subTier}`;}
function tierSh(p){const s=t('tierShort')[TIER_KEYS.indexOf(p.tierKey)]||'?';return NO_SUB.includes(p.tierKey)?s:`${s}${p.subTier}`;}
function laneDisp(k){return t('lanes')[LANE_KEYS.indexOf(k)]||k;}
function showToast(m,d=2200){const e=$('toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),d);}
function setLang(l){lang=l;localStorage.setItem('tm_lang',l);document.querySelectorAll('.lang-btn').forEach(b=>b.classList.toggle('active',b.dataset.lang===l));applyI18n();updateUI();}
function applyI18n(){document.documentElement.lang=lang==='zh'?'zh-CN':lang;$('appTitle').textContent=t('appTitle');$('statLabel').textContent=t('statLabel');$('statLabelSub').textContent=t('statLabel');$('btnAddText').textContent=t('btnAdd');$('btnReset').textContent=t('btnReset');$('btnMatchText').textContent=t('btnMatch');$('emptyTitle').textContent=t('emptyHint');$('emptySubtitle').textContent=t('emptyHintSub');$('placeholderTitle').textContent=t('placeholderTitle');$('placeholderSub').textContent=t('placeholderSub');$('inputName').placeholder=t('inputPlaceholder');for(let i=1;i<=6;i++){const e=$('stepLabel'+i);if(e)e.textContent=t('stepLabels')[i-1];}const ml=$('masterLpLabel');if(ml)ml.textContent=t('masterLpLabel');$('conflictCancelBtn').textContent=t('btnCancel');$('conflictForceBtn').textContent=t('btnForceMatch');$('btnBack').textContent=t('btnBack');$('btnCopyText').textContent=t('btnCopy');$('btnRerollText').textContent=t('btnReroll');$('btnNext').textContent=t('btnNext');$('btnSkip').textContent=t('btnSkip');$('btnFinish').textContent=t('btnFinish');$('sectionLabelPlayers').textContent=t('sectionPlayers');$('algoPreText').textContent=t('algoInfo');$('algoInfoText').textContent=t('algoInfo');$('balanceLabel').textContent=t('balanceLabel');}
function updateUI(){const n=players.length;$('countNum').textContent=n;$('countProgress').style.width=(n/10*100)+'%';$('btnAdd').style.display=n>=10?'none':'';$('btnReset').style.display=n>0?'':'none';$('btnMatchWrap').style.display=n===10?'':'none';$('sectionLabelPlayers').style.display=n>0?'':'none';$('playerListCard').style.display=n>0?'':'none';$('emptyCard').style.display=n>0?'none':'';renderGrid();}
function renderGrid(){const g=$('playerGrid');if(!players.length){g.innerHTML='';return;}g.innerHTML=players.map((p,i)=>{const sc=calcScore(p).toFixed(1),ts=tierDisp(p),sh=tierSh(p),ls=laneDisp(p.laneKey),c=TIER_COLORS[p.tierKey]||'#6B7684';const must=(p.mustWith||[]).map(id=>players.find(x=>x.id===id)?.name).filter(Boolean);const avoid=(p.avoidWith||[]).map(id=>players.find(x=>x.id===id)?.name).filter(Boolean);const tags=[...must.map(n=>`<span class="tag tag-must">+ ${esc(n)}</span>`),...avoid.map(n=>`<span class="tag tag-avoid">- ${esc(n)}</span>`)].join('');return`<div class="player-item"><div class="tier-badge" style="color:${c};background:${c}18">${sh}</div><div class="player-info"><div class="player-name">${esc(p.name)}</div><div class="player-meta">${ts} · ${ls}</div><span class="score-pill">${t('scoreLabel')} ${sc}</span>${tags?`<div class="player-tags">${tags}</div>`:''}</div><button class="btn btn-danger" data-rm="${i}">${t('btnDelete')}</button></div>`;}).join('');g.querySelectorAll('[data-rm]').forEach(b=>b.addEventListener('click',()=>rmPlayer(+b.dataset.rm)));}
function rmPlayer(i){const r=players[i];players.splice(i,1);players.forEach(p=>{p.mustWith=(p.mustWith||[]).filter(id=>id!==r.id);p.avoidWith=(p.avoidWith||[]).filter(id=>id!==r.id);});save();updateUI();showToast(`${r.name} ${t('toastDeleted')}`);}
function resetAll(){if(!confirm(t('confirmReset')))return;players=[];matchResults=[];curIdx=0;save();$('resultScreen').classList.remove('active');$('placeholderCard').style.display='';updateUI();}
function openModal(){if(players.length>=10)return;draft={mustWith:[],avoidWith:[]};step=1;$('stepIndicator').innerHTML=[1,2,3,4,5,6].map(i=>`<div class="step-dot" id="dot${i}"></div>`).join('');goStep(1);$('inputName').value='';$('modalOverlay').classList.add('active');setTimeout(()=>$('inputName').focus(),350);}
function closeModal(){$('modalOverlay').classList.remove('active');}
function goStep(n){for(let i=1;i<=6;i++)$('step'+i).classList.toggle('active',i===n);step=n;for(let i=1;i<=6;i++){const d=$('dot'+i);if(d)d.className='step-dot'+(i<n?' done':i===n?' active':'');}$('modalTitle').textContent=t('stepTitles')[n-1];for(let i=1;i<=6;i++){const e=$('stepLabel'+i);if(e)e.textContent=t('stepLabels')[i-1];}const ml=$('masterLpLabel');if(ml)ml.textContent=t('masterLpLabel');$('btnSkip').textContent=t('btnSkip');$('btnFinish').textContent=t('btnFinish');$('btnNext').textContent=t('btnNext');}
function nextStep(f){if(f===1){const nm=$('inputName').value.trim();if(!nm){showToast(t('nameRequired'));return;}draft.name=nm;buildTier();goStep(2);}else if(f===5){buildAvoid();goStep(6);}}
function buildTier(){const ts=t('tiers');$('tierChips').innerHTML=TIER_KEYS.map((k,i)=>`<div class="chip" style="min-width:76px;text-align:center" data-t="${k}">${ts[i]}</div>`).join('');$('tierChips').querySelectorAll('.chip').forEach(e=>e.addEventListener('click',()=>selTier(e,e.dataset.t)));}
function selTier(el,tk){draft.tierKey=tk;$('tierChips').querySelectorAll('.chip').forEach(c=>c.classList.remove('selected'));el.classList.add('selected');setTimeout(()=>{if(NO_SUB.includes(tk)){if(tk==='마스터')buildMaster();else{draft.subTier=null;draft.masterLpIdx=null;buildLane();goStep(4);}}else{buildSub(tk);goStep(3);}},180);}
function buildSub(tk){const tn=t('tiers')[TIER_KEYS.indexOf(tk)];$('subTierChips').innerHTML=[4,3,2,1].map(n=>`<div class="chip" data-s="${n}">${tn} ${n}</div>`).join('');$('subTierChips').querySelectorAll('.chip').forEach(e=>e.addEventListener('click',()=>selSub(e,+e.dataset.s)));$('masterLpWrap').style.display='none';}
function selSub(el,n){draft.subTier=n;$('subTierChips').querySelectorAll('.chip').forEach(c=>c.classList.remove('selected'));el.classList.add('selected');setTimeout(()=>{buildLane();goStep(4);},180);}
function buildMaster(){$('subTierChips').innerHTML='';$('masterLpWrap').style.display='';$('masterLpLabel').textContent=t('masterLpLabel');const lp=t('masterLp');$('masterLpChips').innerHTML=lp.map((l,i)=>`<div class="chip" data-lp="${i}">${l}</div>`).join('');$('masterLpChips').querySelectorAll('.chip').forEach(e=>e.addEventListener('click',()=>selMLP(e,+e.dataset.lp)));goStep(3);}
function selMLP(el,i){draft.masterLpIdx=i;draft.subTier=null;$('masterLpChips').querySelectorAll('.chip').forEach(c=>c.classList.remove('selected'));el.classList.add('selected');setTimeout(()=>{buildLane();goStep(4);},180);}
function buildLane(){const ls=t('lanes');$('laneChips').innerHTML=LANE_KEYS.map((k,i)=>`<div class="chip" style="min-width:80px;text-align:center" data-l="${k}">${ls[i]}</div>`).join('');$('laneChips').querySelectorAll('.chip').forEach(e=>e.addEventListener('click',()=>selLane(e,e.dataset.l)));}
function selLane(el,lk){draft.laneKey=lk;$('laneChips').querySelectorAll('.chip').forEach(c=>c.classList.remove('selected'));el.classList.add('selected');setTimeout(()=>{buildMust();goStep(5);},180);}
function buildMust(){const w=$('mustChips');if(!players.length){w.innerHTML=`<div style="color:var(--text3);font-size:13px">${t('noPlayers')}</div>`;return;}w.innerHTML=players.map(p=>`<div class="chip" data-id="${p.id}">${esc(p.name)}</div>`).join('');w.querySelectorAll('.chip').forEach(e=>e.addEventListener('click',()=>{const idx=draft.mustWith.indexOf(e.dataset.id);if(idx===-1){draft.mustWith.push(e.dataset.id);e.classList.add('sel-must');}else{draft.mustWith.splice(idx,1);e.classList.remove('sel-must');}}));}
function buildAvoid(){const w=$('avoidChips');if(!players.length){w.innerHTML=`<div style="color:var(--text3);font-size:13px">${t('noPlayers')}</div>`;return;}w.innerHTML=players.map(p=>`<div class="chip" data-id="${p.id}">${esc(p.name)}</div>`).join('');w.querySelectorAll('.chip').forEach(e=>e.addEventListener('click',()=>{const idx=draft.avoidWith.indexOf(e.dataset.id);if(idx===-1){draft.avoidWith.push(e.dataset.id);e.classList.add('sel-avoid');}else{draft.avoidWith.splice(idx,1);e.classList.remove('sel-avoid');}}));}
function finishAdd(){const p={id:Date.now()+Math.random().toString(36).slice(2),name:draft.name,tierKey:draft.tierKey,subTier:draft.subTier||null,masterLpIdx:draft.masterLpIdx??null,laneKey:draft.laneKey||'상관없음',mustWith:draft.mustWith||[],avoidWith:draft.avoidWith||[]};players.push(p);save();updateUI();closeModal();showToast(`${p.name} ${t('toastAdded')}`);}
function doMatch(){if(players.length!==10)return;mode='normal';let r=gather(true,true);if(r.length){matchResults=r;curIdx=0;showRes(r[0]);return;}r=gather(true,false);if(r.length){mode='relaxed';matchResults=r;curIdx=0;showRes(r[0]);return;}showConflict();}
function doReroll(){if(!matchResults.length)return;curIdx=(curIdx+1)%matchResults.length;showRes(matchResults[curIdx]);showToast(`${t('toastCombo')} #${curIdx+1} / ${matchResults.length}`);}
function gather(aC,aB){const c=[];for(let m=0;m<1024;m++){if(pc(m)!==5)continue;const a=[],b=[];for(let i=0;i<10;i++){(m&(1<<i)?a:b).push(players[i]);}if(aC&&!chkC(a,b))continue;const sA=a.reduce((s,p)=>s+calcScore(p),0),sB=b.reduce((s,p)=>s+calcScore(p),0);if(aB){if(Math.abs(Math.max(...a.map(calcScore))-Math.max(...b.map(calcScore)))>5)continue;if(!chkL(a,b))continue;}c.push({teamA:a,teamB:b,scoreA:sA,scoreB:sB,diff:Math.abs(sA-sB)});}c.sort((a,b)=>a.diff-b.diff);return c;}
function pc(n){let c=0;while(n){c+=n&1;n>>=1;}return c;}
function chkC(a,b){const ids=new Set(a.map(p=>p.id));for(const p of[...a,...b]){const inA=ids.has(p.id);for(const m of(p.mustWith||[]))if(inA!==ids.has(m))return false;for(const v of(p.avoidWith||[]))if(inA===ids.has(v))return false;}return true;}
function chkL(a,b){for(const l of LANE_ORD){const f='상관없음',pA=a.filter(p=>p.laneKey===l||p.laneKey===f),pB=b.filter(p=>p.laneKey===l||p.laneKey===f);if(!pA.length||!pB.length)continue;if(Math.abs(Math.max(...pA.map(calcScore))-Math.max(...pB.map(calcScore)))>7)return false;}return true;}
function showConflict(){$('conflictTitle').textContent=t('conflictTitle');$('conflictMsg').textContent=t('conflictMsg');$('conflictCancelBtn').textContent=t('btnCancel');$('conflictForceBtn').textContent=t('btnForceMatch');$('conflictOverlay').classList.add('active');}
function closeConflict(){$('conflictOverlay').classList.remove('active');}
function forceMatch(){closeConflict();mode='forced';matchResults=gather(false,false);curIdx=0;showRes(matchResults.length?matchResults[0]:null);}
function showRes(combo){$('placeholderCard').style.display='none';$('resultScreen').classList.add('active');$('resultTitle').textContent=t('resultTitle');$('balanceLabel').textContent=t('balanceLabel');$('algoInfoText').textContent=t('algoInfo');const err=$('errorMsg'),warn=$('warnMsg'),bal=$('balanceSection'),tw=$('teamsWrapper');if(warn){warn.style.display=mode==='relaxed'?'':'none';if(mode==='relaxed')warn.textContent=t('warnRelaxed');}if(!combo){err.style.display='';err.textContent=t('errorMsg');bal.style.display='none';tw.innerHTML='';$('btnReroll').disabled=true;$('resultSubtitle').textContent=t('noCombo');return;}err.style.display='none';bal.style.display='';$('btnReroll').disabled=matchResults.length<=1;$('resultSubtitle').textContent=`${t('comboLabel')} #${curIdx+1} / ${matchResults.length}`;const flip=Math.random()<.5;const bT=flip?combo.teamA:combo.teamB,rT=flip?combo.teamB:combo.teamA,bS=flip?combo.scoreA:combo.scoreB,rS=flip?combo.scoreB:combo.scoreA;const tot=bS+rS,pct=Math.round(bS/tot*100);$('blueBar').style.width=pct+'%';$('redBar').style.width=(100-pct)+'%';$('bluePct').textContent=pct+'%';$('redPct').textContent=(100-pct)+'%';tw.innerHTML=renderTeam(bT,bS,'blue')+renderTeam(rT,rS,'red');}
function renderTeam(team,score,side){const lbl=side==='blue'?t('blueTeam'):t('redTeam'),cls=side==='blue'?'team-blue':'team-red';const sorted=[...team].sort((a,b)=>{const ai=LANE_ORD.indexOf(a.laneKey),bi=LANE_ORD.indexOf(b.laneKey);return(ai<0?99:ai)-(bi<0?99:bi);});const rows=sorted.map(p=>`<div class="team-player-row"><div class="lane-badge">${LANE_LBL[p.laneKey]||'·'}</div><div class="team-player-name">${esc(p.name)}</div><div class="team-player-tier">${tierDisp(p)} · ${calcScore(p).toFixed(1)}pt</div></div>`).join('');return`<div class="team-card ${cls}"><div class="team-header"><span>${lbl}</span><span class="team-score-badge">${t('totalScore')} ${score.toFixed(1)}</span></div><div class="team-player-list">${rows}</div></div>`;}
function backToMain(){$('resultScreen').classList.remove('active');$('placeholderCard').style.display='';}
function copyDisc(){if(!matchResults.length)return;const c=matchResults[curIdx];if(!c)return;const flip=Math.random()<.5;const bT=flip?c.teamA:c.teamB,rT=flip?c.teamB:c.teamA,bS=flip?c.scoreA:c.scoreB,rS=flip?c.scoreB:c.scoreA;const li=p=>{const i=LANE_ORD.indexOf(p.laneKey);return i<0?99:i;};const fmt=(team,lbl,sc)=>{const s=[...team].sort((a,b)=>li(a)-li(b));return`${lbl} (${t('totalScore')} ${sc.toFixed(1)})\n`+s.map(p=>`  [${LANE_LBL[p.laneKey]||'·'}] ${p.name} — ${tierDisp(p)} (${calcScore(p).toFixed(1)}pt)`).join('\n');};const txt=[`── ${t('resultTitle')} ──`,'',fmt(bT,t('blueTeam'),bS),'',fmt(rT,t('redTeam'),rS),'',`${t('comboLabel')} #${curIdx+1} / ${matchResults.length}`].join('\n');navigator.clipboard.writeText(txt).then(()=>showToast(t('toastCopied'))).catch(()=>{const ta=document.createElement('textarea');ta.value=txt;document.body.appendChild(ta);ta.select();document.execCommand('copy');document.body.removeChild(ta);showToast(t('toastCopied'));});}
document.addEventListener('DOMContentLoaded',()=>{load();applyI18n();updateUI();document.querySelectorAll('.lang-btn').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));$('btnAdd').addEventListener('click',openModal);$('btnReset').addEventListener('click',resetAll);$('btnMatch').addEventListener('click',doMatch);$('modalCloseBtn').addEventListener('click',closeModal);$('modalOverlay').addEventListener('click',e=>{if(e.target===$('modalOverlay'))closeModal();});$('inputName').addEventListener('keydown',e=>{if(e.key==='Enter')nextStep(1);});$('btnNext').addEventListener('click',()=>nextStep(1));$('btnSkip').addEventListener('click',()=>nextStep(5));$('btnFinish').addEventListener('click',finishAdd);$('btnBack').addEventListener('click',backToMain);$('btnCopy').addEventListener('click',copyDisc);$('btnReroll').addEventListener('click',doReroll);$('conflictCloseBtn').addEventListener('click',closeConflict);$('conflictCancelBtn').addEventListener('click',closeConflict);$('conflictForceBtn').addEventListener('click',forceMatch);});
