'use strict';
const I18N={ko:{appTitle:'롤토체스 더블업',statLabel:'명 등록됨',btnAdd:'참가자 추가',btnReset:'초기화',btnMatch:'팀 밸런스 맞추기',btnBack:'돌아가기',btnCopy:'디스코드 복사',btnNext:'다음',btnDelete:'삭제',scoreLabel:'점수',toastCopied:'클립보드에 복사됐어요',toastAdded:'등록 완료!',toastDeleted:'삭제됨',confirmReset:'모든 참가자를 초기화할까요?',emptyHint:'참가자를 추가해주세요',emptyHintSub:'인원을 등록할 수 있어요',nameRequired:'이름을 입력해주세요',inputPlaceholder:'소환사 이름 입력',tftCountLabel:'참가 인원',resultTitle:'더블업 조 편성 완료',resultSub:'상하 균등 분배 매칭',teamLabel:'팀',avgLabel:'평균',placeholderTitle:'조 편성 결과가 여기에 표시됩니다',placeholderSub:'인원을 모두 등록하고 팀 밸런스 맞추기를 눌러주세요',sectionPlayers:'참가자',stepLabels:['Step 1 — 이름','Step 2 — 티어','Step 3 — 세부 티어'],stepTitles:['이름 입력','티어 선택','세부 티어'],masterLpLabel:'마스터 LP 구간',tiers:['아이언','브론즈','실버','골드','플래티넘','에메랄드','다이아몬드','마스터','그랜드마스터','챌린저'],tierShort:['I','B','S','G','P','E','D','M','GM','C'],masterLp:['저점 (0~200LP)','고점 (200LP+)'],copyHeader:'[롤토체스 더블업 조 편성 결과]',needFull:'설정한 인원수를 채워주세요',algoInfo:'알고리즘 안내: 더블업 모드의 특성을 고려하여, 참가자들을 티어 순으로 정렬한 뒤 최상위 티어와 최하위 티어를 순차적으로 한 조로 묶는 상하 균등 분배 방식을 사용합니다. 이를 통해 각 2인조 팀들의 평균 실력 차이를 가장 공평하게 맞춥니다.'},
en:{appTitle:'TFT Double Up',statLabel:'registered',btnAdd:'Add Player',btnReset:'Reset',btnMatch:'Balance Teams',btnBack:'Back',btnCopy:'Copy for Discord',btnNext:'Next',btnDelete:'Remove',scoreLabel:'Score',toastCopied:'Copied!',toastAdded:'added!',toastDeleted:'removed',confirmReset:'Reset all?',emptyHint:'Add players to get started',emptyHintSub:'Register players',nameRequired:'Enter a name',inputPlaceholder:'Summoner name',tftCountLabel:'Players',resultTitle:'Double Up Teams Ready',resultSub:'Balanced pair matching',teamLabel:'Team',avgLabel:'Avg',placeholderTitle:'Results will appear here',placeholderSub:'Register all players and click Balance Teams',sectionPlayers:'Players',stepLabels:['Step 1 — Name','Step 2 — Tier','Step 3 — Sub Tier'],stepTitles:['Name','Tier','Sub Tier'],masterLpLabel:'Master LP',tiers:['Iron','Bronze','Silver','Gold','Platinum','Emerald','Diamond','Master','Grandmaster','Challenger'],tierShort:['I','B','S','G','P','E','D','M','GM','C'],masterLp:['Low LP','High LP'],copyHeader:'[TFT Double Up Team Results]',needFull:'Please fill the set player count',algoInfo:"Algorithm Guide: Considering the nature of Double Up mode, participants are sorted by tier, and the 'highest tier' and 'lowest tier' players are sequentially paired. This ensures the most equitable balance of average skill across all 2-player teams."},
ja:{appTitle:'TFTダブルアップ',statLabel:'人登録済み',btnAdd:'追加',btnReset:'リセット',btnMatch:'バランス調整',btnBack:'戻る',btnCopy:'コピー',btnNext:'次へ',btnDelete:'削除',scoreLabel:'スコア',toastCopied:'コピーしました',toastAdded:'登録完了',toastDeleted:'削除',confirmReset:'リセットしますか？',emptyHint:'追加してください',emptyHintSub:'プレイヤーを登録',nameRequired:'名前を入力',inputPlaceholder:'サモナー名',tftCountLabel:'参加人数',resultTitle:'ダブルアップ編成完了',resultSub:'均等分配マッチング',teamLabel:'チーム',avgLabel:'平均',placeholderTitle:'結果がここに表示されます',placeholderSub:'全員を登録してバランス調整を押してください',sectionPlayers:'プレイヤー',stepLabels:['Step 1 — 名前','Step 2 — ティア','Step 3 — サブティア'],stepTitles:['名前','ティア','サブティア'],masterLpLabel:'マスターLP',tiers:['アイアン','ブロンズ','シルバー','ゴールド','プラチナ','エメラルド','ダイヤ','マスター','グラマス','チャレ'],tierShort:['I','B','S','G','P','E','D','M','GM','C'],masterLp:['低LP','高LP'],copyHeader:'[TFTダブルアップ編成結果]',needFull:'設定人数を満たしてください',algoInfo:'アルゴリズム案内: ダブルアップの特性を考慮し、参加者をティア順に並べ、最上位と最下位を順次ペアにする均等分配方式を使用します。'},
zh:{appTitle:'云顶双人作战',statLabel:'已注册',btnAdd:'添加',btnReset:'重置',btnMatch:'平衡队伍',btnBack:'返回',btnCopy:'复制',btnNext:'下一步',btnDelete:'删除',scoreLabel:'分数',toastCopied:'已复制',toastAdded:'完成',toastDeleted:'已删除',confirmReset:'确定重置？',emptyHint:'请添加玩家',emptyHintSub:'注册玩家',nameRequired:'请输入',inputPlaceholder:'召唤师名',tftCountLabel:'参加人数',resultTitle:'双人作战编排完成',resultSub:'均衡分配匹配',teamLabel:'队伍',avgLabel:'平均',placeholderTitle:'结果将显示在这里',placeholderSub:'注册全部玩家后点击平衡队伍',sectionPlayers:'玩家',stepLabels:['Step 1 — 名称','Step 2 — 段位','Step 3 — 细分'],stepTitles:['名称','段位','细分'],masterLpLabel:'大师LP',tiers:['黑铁','黄铜','白银','黄金','铂金','翡翠','钻石','宗师','王者','挑战者'],tierShort:['I','B','S','G','P','E','D','M','GM','C'],masterLp:['低LP','高LP'],copyHeader:'[云顶双人作战编排结果]',needFull:'请填满设定人数',algoInfo:'算法说明: 考虑双人作战特性，按段位排序后将最高与最低段位依次配对，确保各2人组平均实力差异最小。'}};
const TIER_KEYS=['아이언','브론즈','실버','골드','플래티넘','에메랄드','다이아몬드','마스터','그랜드마스터','챌린저'],TIER_COLORS={'아이언':'#8B8B8B','브론즈':'#A0522D','실버':'#708090','골드':'#B8860B','플래티넘':'#2E8B57','에메랄드':'#00A86B','다이아몬드':'#4169E1','마스터':'#9B59B6','그랜드마스터':'#C0392B','챌린저':'#E67E22'},SCORES={'아이언':[1,1.2,1.4,1.6],'브론즈':[2,2.2,2.4,2.6],'실버':[3,3.3,3.6,3.9],'골드':[4.5,4.9,5.3,5.7],'플래티넘':[6.5,7,7.5,8],'에메랄드':[9.5,10.2,10.9,11.6],'다이아몬드':[13.5,14.5,15.5,16.5],'마스터':null,'그랜드마스터':32,'챌린저':40},MLP={0:21,1:26},NO_SUB=['마스터','그랜드마스터','챌린저'];
let players=[],tftTeams=[],tftCount=8,draft={},step=1,lang='ko';
const t=k=>I18N[lang]?.[k]??I18N.ko[k]??k,$=id=>document.getElementById(id),esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function showToast(m,d=2200){const e=$('toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),d);}
function save(){localStorage.setItem('tft_players',JSON.stringify(players))}
function load(){try{players=JSON.parse(localStorage.getItem('tft_players')||'[]')}catch{players=[]}lang=localStorage.getItem('tm_lang')||'ko';tftCount=parseInt(localStorage.getItem('tft_count')||'8');}
function calcScore(p){const k=p.tierKey;if(k==='그랜드마스터')return 32;if(k==='챌린저')return 40;if(k==='마스터')return MLP[p.masterLpIdx]??21;const a=SCORES[k];if(!a)return 0;const sub=parseInt(p.subTier);if(isNaN(sub))return a[0];return a[Math.max(0,Math.min(3,4-sub))];}
function tierDisp(p){const ts=t('tiers'),i=TIER_KEYS.indexOf(p.tierKey),n=ts[i]||p.tierKey;if(NO_SUB.includes(p.tierKey))return p.tierKey==='마스터'?`${n} (${t('masterLp')[p.masterLpIdx]||''})`:n;return`${n} ${p.subTier||''}`;}
function tierSh(p){const s=t('tierShort')[TIER_KEYS.indexOf(p.tierKey)]||'?';return NO_SUB.includes(p.tierKey)?s:`${s}${p.subTier||''}`;}
function setLang(l){lang=l;localStorage.setItem('tm_lang',l);document.querySelectorAll('.lang-btn').forEach(b=>b.classList.toggle('active',b.dataset.lang===l));applyI18n();updateUI();}
function applyI18n(){document.documentElement.lang=lang==='zh'?'zh-CN':lang;$('appTitle').textContent=t('appTitle');$('statLabel').textContent=t('statLabel');$('statLabelSub').textContent=t('statLabel');$('btnAddText').textContent=t('btnAdd');$('btnReset').textContent=t('btnReset');$('btnMatchText').textContent=t('btnMatch');$('emptyTitle').textContent=t('emptyHint');$('placeholderTitle').textContent=t('placeholderTitle');$('placeholderSub').textContent=t('placeholderSub');$('sectionLabelPlayers').textContent=t('sectionPlayers');$('tftCountLabel').textContent=t('tftCountLabel');$('btnBack').textContent=t('btnBack');$('btnCopyText').textContent=t('btnCopy');$('btnNext').textContent=t('btnNext');$('algoPreText').textContent=t('algoInfo');$('algoInfoText').textContent=t('algoInfo');$('inputName').placeholder=t('inputPlaceholder');for(let i=1;i<=3;i++){const e=$('stepLabel'+i);if(e)e.textContent=t('stepLabels')[i-1];}const ml=$('masterLpLabel');if(ml)ml.textContent=t('masterLpLabel');}
function updateUI(){const max=tftCount,n=players.length;$('countNum').textContent=n;$('countTotal').textContent=max;$('countProgress').style.width=(n/max*100)+'%';$('btnAdd').style.display=n>=max?'none':'';$('btnReset').style.display=n>0?'':'none';$('btnMatchWrap').style.display=n===max?'':'none';$('sectionLabelPlayers').style.display=n>0?'':'none';$('playerListCard').style.display=n>0?'':'none';$('emptyCard').style.display=n>0?'none':'';$('emptySubtitle').textContent=`${max} ${t('statLabel')}`;renderGrid();}
function renderGrid(){const g=$('playerGrid');if(!players.length){g.innerHTML='';return;}g.innerHTML=players.map((p,i)=>{const sc=calcScore(p).toFixed(1),ts=tierDisp(p),sh=tierSh(p),c=TIER_COLORS[p.tierKey]||'#6B7684';return`<div class="player-item"><div class="tier-badge" style="color:${c};background:${c}18">${sh}</div><div class="player-info"><div class="player-name">${esc(p.name)}</div><div class="player-meta">${ts}</div><span class="score-pill">${t('scoreLabel')} ${sc}</span></div><button class="btn btn-danger" data-rm="${i}">${t('btnDelete')}</button></div>`;}).join('');g.querySelectorAll('[data-rm]').forEach(b=>b.addEventListener('click',()=>rmPlayer(+b.dataset.rm)));}
function rmPlayer(i){const r=players[i];players.splice(i,1);save();updateUI();showToast(`${r.name} ${t('toastDeleted')}`);}
function resetAll(){if(!confirm(t('confirmReset')))return;players=[];tftTeams=[];save();$('resultScreen').classList.remove('active');$('placeholderCard').style.display='';updateUI();}
function openModal(){if(players.length>=tftCount)return;draft={};step=1;$('stepIndicator').innerHTML=[1,2,3].map(i=>`<div class="step-dot" id="dot${i}"></div>`).join('');goStep(1);$('inputName').value='';$('modalOverlay').classList.add('active');setTimeout(()=>$('inputName').focus(),350);}
function closeModal(){$('modalOverlay').classList.remove('active');}
function goStep(n){for(let i=1;i<=3;i++)$('step'+i).classList.toggle('active',i===n);step=n;for(let i=1;i<=3;i++){const d=$('dot'+i);if(d)d.className='step-dot'+(i<n?' done':i===n?' active':'');}$('modalTitle').textContent=t('stepTitles')[n-1];for(let i=1;i<=3;i++){const e=$('stepLabel'+i);if(e)e.textContent=t('stepLabels')[i-1];}const ml=$('masterLpLabel');if(ml)ml.textContent=t('masterLpLabel');$('btnNext').textContent=t('btnNext');}
function nextStep(f){if(f===1){const nm=$('inputName').value.trim();if(!nm){showToast(t('nameRequired'));return;}draft.name=nm;buildTier();goStep(2);}}
function buildTier(){const ts=t('tiers');$('tierChips').innerHTML=TIER_KEYS.map((k,i)=>`<div class="chip" style="min-width:76px;text-align:center" data-t="${k}">${ts[i]}</div>`).join('');$('tierChips').querySelectorAll('.chip').forEach(e=>e.addEventListener('click',()=>selTier(e,e.dataset.t)));}
function selTier(el,tk){draft.tierKey=tk;$('tierChips').querySelectorAll('.chip').forEach(c=>c.classList.remove('selected'));el.classList.add('selected');setTimeout(()=>{if(NO_SUB.includes(tk)){if(tk==='마스터')buildMaster();else{draft.subTier=null;draft.masterLpIdx=null;finishAdd();}}else{buildSub(tk);goStep(3);}},180);}
function buildSub(tk){const tn=t('tiers')[TIER_KEYS.indexOf(tk)];$('subTierChips').innerHTML=[4,3,2,1].map(n=>`<div class="chip" data-s="${n}">${tn} ${n}</div>`).join('');$('subTierChips').querySelectorAll('.chip').forEach(e=>e.addEventListener('click',()=>selSub(e,+e.dataset.s)));$('masterLpWrap').style.display='none';}
function selSub(el,n){draft.subTier=n;$('subTierChips').querySelectorAll('.chip').forEach(c=>c.classList.remove('selected'));el.classList.add('selected');setTimeout(()=>finishAdd(),180);}
function buildMaster(){$('subTierChips').innerHTML='';$('masterLpWrap').style.display='';$('masterLpLabel').textContent=t('masterLpLabel');const lp=t('masterLp');$('masterLpChips').innerHTML=lp.map((l,i)=>`<div class="chip" data-lp="${i}">${l}</div>`).join('');$('masterLpChips').querySelectorAll('.chip').forEach(e=>e.addEventListener('click',()=>selMLP(e,+e.dataset.lp)));goStep(3);}
function selMLP(el,i){draft.masterLpIdx=i;draft.subTier=null;$('masterLpChips').querySelectorAll('.chip').forEach(c=>c.classList.remove('selected'));el.classList.add('selected');setTimeout(()=>finishAdd(),180);}
function finishAdd(){const p={id:Date.now()+Math.random().toString(36).slice(2),name:draft.name,tierKey:draft.tierKey,subTier:draft.subTier||null,masterLpIdx:draft.masterLpIdx??null};players.push(p);save();updateUI();closeModal();showToast(`${p.name} ${t('toastAdded')}`);}
function doMatch(){if(players.length!==tftCount){showToast(t('needFull'));return;}const sorted=[...players].sort((a,b)=>calcScore(b)-calcScore(a));tftTeams=[];const half=sorted.length/2;for(let i=0;i<half;i++)tftTeams.push([sorted[i],sorted[sorted.length-1-i]]);showResult();}
function showResult(){$('placeholderCard').style.display='none';$('resultScreen').classList.add('active');$('resultTitle').textContent=t('resultTitle');$('resultSubtitle').textContent=t('resultSub');$('algoInfoText').textContent=t('algoInfo');const w=$('teamsWrapper');w.innerHTML=tftTeams.map((pair,i)=>{const avg=((calcScore(pair[0])+calcScore(pair[1]))/2).toFixed(1);const rows=pair.map(p=>`<div class="tft-player-row"><div class="tier-badge" style="color:${TIER_COLORS[p.tierKey]||'#6B7684'};background:${(TIER_COLORS[p.tierKey]||'#6B7684')}18;width:32px;height:32px;font-size:11px">${tierSh(p)}</div><div class="tft-player-name">${esc(p.name)}</div><div class="tft-player-tier">${tierDisp(p)} · ${calcScore(p).toFixed(1)}pt</div></div>`).join('');return`<div class="tft-team-card"><div class="tft-team-header"><span>${t('teamLabel')} ${i+1}</span><span class="tft-team-avg">${t('avgLabel')} ${avg}pt</span></div><div class="tft-team-players">${rows}</div></div>`;}).join('');}
function backToMain(){$('resultScreen').classList.remove('active');$('placeholderCard').style.display='';}
function copyDisc(){if(!tftTeams.length)return;const lines=tftTeams.map((pair,i)=>`* ${t('teamLabel')} ${i+1}: ${pair[0].name} (${tierDisp(pair[0])}), ${pair[1].name} (${tierDisp(pair[1])})`);const txt=['**'+t('copyHeader')+'**','',...lines].join('\n');navigator.clipboard.writeText(txt).then(()=>showToast(t('toastCopied'))).catch(()=>{const ta=document.createElement('textarea');ta.value=txt;document.body.appendChild(ta);ta.select();document.execCommand('copy');document.body.removeChild(ta);showToast(t('toastCopied'));});}
document.addEventListener('DOMContentLoaded',()=>{load();$('tftCountSelect').value=String(tftCount);applyI18n();updateUI();
document.querySelectorAll('.lang-btn').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));
$('tftCountSelect').addEventListener('change',e=>{tftCount=+e.target.value;localStorage.setItem('tft_count',String(tftCount));if(players.length>tftCount){players=players.slice(0,tftCount);save();}$('resultScreen').classList.remove('active');$('placeholderCard').style.display='';updateUI();});
$('btnAdd').addEventListener('click',openModal);$('btnReset').addEventListener('click',resetAll);$('btnMatch').addEventListener('click',doMatch);
$('modalCloseBtn').addEventListener('click',closeModal);$('modalOverlay').addEventListener('click',e=>{if(e.target===$('modalOverlay'))closeModal();});
$('inputName').addEventListener('keydown',e=>{if(e.key==='Enter')nextStep(1);});$('btnNext').addEventListener('click',()=>nextStep(1));
$('btnBack').addEventListener('click',backToMain);$('btnCopy').addEventListener('click',copyDisc);});
